---
- name: Check which plugins are installed
  find:
    file_type: directory
    recurse: false
    paths: "{{ grafana_data_dir }}/plugins"
  register: installed_plugins

- name: Install image renderer plugin dependencies
  package:
    name: "{{ grafana_image_renderer_dependancies }}"
    state: present
  register: _install_ir_plugin_dep_packages
  until: _install_ir_plugin_dep_packages is succeeded
  retries: 5
  delay: 2
  when: "'grafana-image-renderer' in {{ grafana_plugins }}"

- name: Install plugins
  become: true
  command: "grafana-cli --pluginsDir {{ grafana_data_dir }}/plugins plugins install {{ item }}"
  args:
    creates: "{{ grafana_data_dir }}/plugins/{{ item }}"
  with_items: "{{ grafana_plugins | difference(installed_plugins.files) }}"
  register: _plugin_install
  until: _plugin_install is succeeded
  retries: 5
  delay: 2
  notify:
    - restart grafana
